title: धम्म लेख
description: धम्म लेख ब्लॉग में पढ़ें बुद्ध के उपदेश, पंचशील, ध्यान और जीवन में सही मार्गदर्शन सरल भाषा में।

url: https://siddharthvishwamitra.github.io/dhammablog
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about
    - title: Contact
      url: /contact

social:
    twitter: dhammaApp
    facebook: bahdORG
    email: dhammaApp@gmail.com

google_analytics: "#"

disqus:
    shortname: dhamma-blog
